# Generated by Django 4.0.2 on 2022-03-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=10)),
                ('position', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=2)),
                ('edu', models.CharField(max_length=10)),
                ('birthday', models.DateField()),
                ('entry', models.DateField()),
            ],
        ),
    ]
